script:
- mkdir build
- cmake -DCMAKE_CXX_COMPILER=$CC ..
- make cirkit revkit

matrix:
  include:
  - os: linux
    dist: trusty
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - CC=g++-7
  - os: osx
    osx_image: xcode8.3
    compiler: gcc
    before_install:
      - brew update
      - brew cask uninstall oclint
      - brew install gcc@7
    env:
      - CC=/usr/local/Cellar/gcc@7/7.3.0/bin/g++-7
