branches:
  only:
    - develop

sudo: required
dist: trusty

language: cpp
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DPYBIND11_PYTHON_VERSION=2.7 ..
  - make cirkit

addons: 
  apt: 
    packages: libboost-all-dev

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5