language: python
dist: trusty
sudo: false

script:
- python -m pip install --upgrade pip setuptools wheel
- python -m pip install pybind11
- cd dist/cirkit
- python setup.py bdist_wheel
- cd ../revkit
- python setup.py bdist_wheel
- cd ../../

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
  artifacts:
    s3_region: us-west-2
    paths:
    - $(ls ./dist/cirkit/dist/*.whl)
    - $(ls ./dist/revkit/dist/*.whl)

env:
- CC=g++-7

matrix:
  include:
  - os: linux
    python: "2.7"
  - os: linux
    python: "3.4"
  - os: linux
    python: "3.5"
  - os: linux
    python: "3.6"
