branches:
  only:
    - develop

sudo: required
dist: trusty

language: cpp

addons: 
  apt: 
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - libboost-all-dev
      - ninja-build

script:
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_CXX_COMPILER=g++-5 -DPYBIND11_PYTHON_VERSION=2.7 -Denable_cirkit-addon-reversible=ON ..
  - ninja revkit
