language: python
dist: trusty
sudo: false

install:
- python -m pip install --upgrade pip setuptools wheel
- python -m pip install pybind11
- python setup.py sdist bdist_wheel

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
  artifacts:
    paths:
    - ./dist/*.whl

env:
- CC=g++7
- CXX=g++7

matrix:
  include:
  - os: linux
    python: "2.7"
  - os: linux
    python: "3.6"
