version: '3.1b.{build}'

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release

environment:
  matrix:
    #- PYTHON: "C:\\Python27-x64"
    #- PYTHON: "C:\\Python34-x64"
    #- PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  - git submodule update --init --recursive
  - "%PYTHON%\\python.exe -m pip install pybind11"
  - "%PYTHON%\\python.exe -m pip install wheel"
  - echo "Installed SDKs:"
  - ps: "ls \"C:/Program Files (x86)/Microsoft SDKs/Windows\""

build: off

after_test:
  - "cd dist\\cirkit"
  - "%PYTHON%\\python.exe setup.py bdist_wheel"
  - "cd ..\\.."
  - "cd dist\\revkit"
  - "%PYTHON%\\python.exe setup.py bdist_wheel"
  - "cd ..\\.."

artifacts:
  - path: dist\cirkit\dist\*
  - path: dist\revkit\dist\*
